Repository team-gingerbread/movie-cookie, pull requests merged in 2023-12, with the labels that each got.

#8 ✨ADD: 좋아요, 본영화, 볼영화 api 추가 - 인증 미구현
  movieinfo/migrations/0001_initial.py
  movieinfo/migrations/0002_testwatchlistmovie_testwatchedmovie_testlikemovie.py
  movieinfo/models.py
  movieinfo/serializers.py
  movieinfo/urls.py
  movieinfo/views.py
  recommend/migrations/0001_initial.py
Labels: enhancement

#10 ✨Community 게시물CRUD API 구현
  community/__init__.py
  community/admin.py
  community/apps.py
  community/models.py
  community/serializers.py
  community/tests.py
  community/urls.py
  community/views.py
  config/settings.py
  config/urls.py
Labels: enhancement

#19 ✨Community 게시물 검색기능 구현
  community/views.py
Labels: enhancement

#20 Recommend 영화추천 뷰 작성
  .gitignore
  config/settings.py
  config/urls.py
  recommend/migrations/0001_initial.py
  recommend/models.py
  recommend/serializers.py
  recommend/views.py
  requirements.txt
  static/foreign.csv
  static/korean.csv
Labels: enhancement

#23 첫번째 배포
  .gitignore
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_remove_userprofile_password_and_more.py
  accounts/migrations/0003_remove_userprofile_id_and_more.py
  accounts/migrations/0004_userprofile_id_alter_userprofile_user.py
  accounts/migrations/0005_alter_userprofile_id.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/profile_edit.html
  accounts/templates/accounts/signup.html
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  community/__init__.py
  community/admin.py
  community/apps.py
  community/migrations/0001_initial.py
  community/migrations/__init__.py
  community/models.py
  community/serializers.py
  community/tests.py
  community/urls.py
  community/views.py
  config/settings.py
  config/urls.py
  movieinfo/migrations/0001_initial.py
  movieinfo/migrations/0002_testwatchlistmovie_testwatchedmovie_testlikemovie.py
  movieinfo/models.py
  movieinfo/serializers.py
  movieinfo/urls.py
  movieinfo/views.py
  recommend/migrations/0001_initial.py
  recommend/models.py
  recommend/serializers.py
  recommend/views.py
  requirements.txt
  static/foreign.csv
  static/korean.csv
Labels: deploy

#25 🚀ADD: CI/CD를 위한 yaml 파일 생성
  .github/workflows/main.yml
Labels: deploy

#26 Recommend 유저가중치 추가 & 코드정리
  config/settings.py
  config/urls.py
  recommend/migrations/0001_initial.py
  recommend/models.py
  recommend/schema_examples.py
  recommend/serializers.py
  recommend/views.py
Labels: enhancement

#28 🎨 UPDATE: csv, views 수정 (장르정리)
  recommend/views.py
  static/foreign.csv
Labels: enhancement

#29 ✨ADD: 영화 분석 메시지 GPT추가
  movieinfo/detail_summary_with_GPT.py
  movieinfo/migrations/0003_gptanalysis.py
  movieinfo/models.py
  movieinfo/serializers.py
  movieinfo/urls.py
  movieinfo/views.py
Labels: enhancement

#30 🚀 프론트엔드 fetch 테스트를 위한 배포
  config/settings.py
  config/urls.py
  movieinfo/detail_summary_with_GPT.py
  movieinfo/migrations/0003_gptanalysis.py
  movieinfo/models.py
  movieinfo/serializers.py
  movieinfo/urls.py
  movieinfo/views.py
  recommend/migrations/0001_initial.py
  recommend/models.py
  recommend/schema_examples.py
  recommend/serializers.py
  recommend/views.py
  static/foreign.csv
Labels: deploy

#32 ⚡UPDATE: msa refactoring
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_remove_userprofile_password_and_more.py
  accounts/migrations/0003_remove_userprofile_id_and_more.py
  accounts/migrations/0004_userprofile_id_alter_userprofile_user.py
  accounts/migrations/0005_alter_userprofile_id.py
  accounts/models.py
  accounts/serializers.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/profile_edit.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  community/migrations/0002_rename_context_post_content.py
  config/settings.py
  recommend/migrations/0002_remove_recommend_user.py
Labels: enhancement

#35 :zap:UPDATE: 모델 정규화 작업 및 정규화에 따른 DB 저장 방법 수정
  movieinfo/models.py
  movieinfo/utils.py
  movieinfo/views.py
Labels: enhancement

#39 ⚡️ UPDATE: 추천 모델 정규화에 맞춰 변경
  add_genre.py
  movieinfo/migrations/0001_initial.py
  movieinfo/migrations/0002_testwatchlistmovie_testwatchedmovie_testlikemovie.py
  movieinfo/migrations/0003_gptanalysis.py
  recommend/migrations/0001_initial.py
  recommend/migrations/0002_remove_recommend_user.py
  recommend/models.py
  recommend/schema_examples.py
  recommend/serializers.py
  recommend/views.py
Labels: enhancement

#41 🎨 UPDATE: recommend id도 나오게 수정, title 필수x 변경
  recommend/migrations/0001_initial.py
  recommend/models.py
  recommend/schema_examples.py
  recommend/serializers.py
  recommend/views.py
Labels: enhancement

#46 🐛 UPDATE: 응답오류, 독스트링 수정
  recommend/permissions.py
  recommend/serializers.py
  recommend/views.py
Labels: bug

#48 🐛FIX: 저장 제외한 특정 장르의 영화가 저장되는 문제 해결, VOD의 잘못된 주소를 저장하는 문제 해결
  movieinfo/utils.py
Labels: bug

#51 ⚡UPDATE: accounts model update
  accounts/models.py
Labels: bug

#52 :zap:UPDATE: DB 변경 sqlite > postgreSQL
  accounts/migrations/0004_remove_user_ganre_user_genre_watchlistmovie_and_more.py
  config/settings.py
  movieinfo/models.py
  movieinfo/utils.py
  movieinfo/views.py
  requirements.txt
Labels: enhancement

#55 ⚡️ UPDATE: 생성일도 나오게 수정, 가중치부분 체크
  recommend/schema_examples.py
  recommend/serializers.py
  recommend/views.py
Labels: enhancement

#56 :zap:UPDATE: accounts 앱과 연결, movieinfo 측에서 유저 선호도 정보 저장, 한줄평의 유저 정보 저장
  config/settings.py
  movieinfo/migrations/0002_remove_testwatchedmovie_movie_and_more.py
  movieinfo/models.py
  movieinfo/permissions.py
  movieinfo/serializers.py
  movieinfo/views.py
Labels: enhancement

#58 🐛FIX: 한줄평에서 노출되는 유저 정보 설정
  movieinfo/serializers.py
Labels: bug

#60 🐛FIX: onelinecritic의 저장 문제 해결
  movieinfo/serializers.py
  movieinfo/views.py
Labels: bug

#62 ⚡️ UPDATE: TDD추가, poster url관련수정
  recommend/tests.py
  recommend/views.py
Labels: enhancement

#68 :zap:UPDATE: 좋아요 기능 url 구조 변경
  config/settings.py
  movieinfo/views.py
Labels: enhancement

#70 🐛FIX: 직관적이지 않았던 url 수정 및 좋아요 기능 retrive 활성화
  movieinfo/views.py
Labels: bug

#71 Recommend csv자동업데이트 기능 넣기 & 가중치 업뎃
  add_genre.py
  config/settings.py
  recommend/cron.py
  recommend/permissions.py
  recommend/schema_examples.py
  recommend/views.py
  requirements.txt
  static/foreign.csv
  static/korean.csv
Labels: enhancement

#72 🚀 백엔드 기능 배포
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_initial.py
  accounts/migrations/0002_remove_userprofile_password_and_more.py
  accounts/migrations/0003_remove_userprofile_id_and_more.py
  accounts/migrations/0004_userprofile_id_alter_userprofile_user.py
  accounts/migrations/0005_alter_userprofile_id.py
  accounts/models.py
  accounts/permissions.py
  accounts/serializers.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/profile_edit.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  community/migrations/0001_initial.py
  community/models.py
  community/serializers.py
  community/views.py
  config/settings.py
  movieinfo/detail_summary_with_GPT.py
  movieinfo/migrations/0001_initial.py
  movieinfo/migrations/0002_testwatchlistmovie_testwatchedmovie_testlikemovie.py
  movieinfo/migrations/0003_gptanalysis.py
  movieinfo/models.py
  movieinfo/permissions.py
  movieinfo/serializers.py
  movieinfo/urls.py
  movieinfo/utils.py
  movieinfo/views.py
  recommend/cron.py
  recommend/migrations/0001_initial.py
  recommend/models.py
  recommend/permissions.py
  recommend/schema_examples.py
  recommend/serializers.py
  recommend/tests.py
  recommend/views.py
  requirements.txt
  static/foreign.csv
  static/korean.csv
Labels: deploy

#73 🎨 UPDATE: requirements 수정
  requirements.txt
Labels: deploy

#74 ✨ADD: 유저가 좋아요한 영화, 볼 영화, 본 영화 조회기능 추가
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
Labels: enhancement

#75 accounts 기능 추가도 배포
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
Labels: deploy
